// Template email (MTS §7). Semua data yang ditampilkan di-escape.
const esc = (t: unknown) => String(t ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
const wrap = (title: string, body: string) =>
  `<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet"><div style="font-family:Poppins,Arial,sans-serif;max-width:480px;color:#1C2B44"><h2 style="color:#0F2F5E">${esc(title)}</h2>${body}<p style="color:#4B5A70;font-size:12px;margin-top:24px">English Inspira</p></div>`;
const btn = (href: string, label: string) => `<p><a href="${esc(href)}" style="display:inline-block;background:#1B5FB8;color:#fff;padding:12px 20px;border-radius:10px;text-decoration:none;font-weight:600">${esc(label)}</a></p>`;
const fmt = (d: unknown) => new Date(String(d)).toLocaleString("en-GB", { dateStyle: "full", timeStyle: "short", timeZone: "Asia/Jakarta" });

type D = Record<string, unknown>;
export const TEMPLATES = {
  // Kode ada di judul: tiap email unik sehingga Gmail tidak menumpuknya dengan kode lama (penyebab "Kode salah").
  otp: (d: D) => ({ subject: `${String(d.code)} is your English Inspira sign-in code`, html: wrap("Sign-in code", `<p>Use the code below. Valid for 5 minutes. Do not share it with anyone.</p><p style="font-size:32px;font-weight:800;letter-spacing:8px;color:#1B5FB8">${esc(d.code)}</p>`) }),
  verify_email: (d: D) => ({ subject: `${String(d.code)} is your English Inspira verification code`, html: wrap("Verify your email", `<p>Use the code below to finish creating your account. Valid for 5 minutes.</p><p style="font-size:30px;font-weight:700;letter-spacing:6px;color:#0F2F5E">${esc(d.code)}</p><p style="color:#4B5A70;font-size:13px">If you did not create an account, ignore this email.</p>`) }),
  account_exists: (d: D) => ({ subject: "You already have an English Inspira account", html: wrap("You already have an account", `<p>Someone tried to create an account with this email. You already have one, so no new account was made.</p>${btn(String(d.link), "Sign in")}<p style="color:#4B5A70;font-size:13px">Forgot your password? Use "Forgot password" on the sign-in page. If this was not you, ignore this email.</p>`) }),
  password_reset: (d: D) => ({ subject: "Reset your English Inspira password", html: wrap("Reset your password", `<p>Click the button below to set a new password. The link is valid for 30 minutes and works once.</p>${btn(String(d.link), "Set a new password")}<p style="color:#4B5A70;font-size:13px">If you did not request this, ignore this email. Your password stays the same.</p>`) }),
  invitation: (d: D) => ({ subject: `Invitation to the TOEFL ITP preparation program from ${d.institution}`, html: wrap(`Invitation from ${d.institution}`, `<p>Hello${d.name ? ` ${esc(d.name)}` : ""}, you are invited to join the TOEFL ITP preparation program by <b>${esc(d.institution)}</b>.</p><p>Sign in with this email; we will send a 6-digit code to your inbox. The link is valid until ${esc(fmt(d.expiresAt))}.</p>${btn(String(d.link), "Get started")}`) }),
  placement_result: (d: D) => ({ subject: "Your placement test result", html: wrap("Placement result", `<p>Your estimated score is <b>${esc(d.score)}</b>, level <b>${esc(d.level)}</b>. Coaching quota: <b>${esc(d.quota)}</b> sessions.</p><p>Your result analysis and a study plan for the topics you need to strengthen are available in the app.</p>${btn(String(d.link), "See results")}`) }),
  level_up: (d: D) => ({ subject: "Congratulations, you leveled up", html: wrap("Level up", `<p>Your simulation result meets the requirements. You are now at the <b>${esc(d.level)}</b> level with a new coaching quota of <b>${esc(d.quota)}</b> sessions.</p><p>Your study plan has been updated.</p>${btn(String(d.link), "Go to home")}`) }),
  contract_expiring: (d: D) => ({ subject: `The ${d.name} program contract ends in ${d.days} days`, html: wrap("Contracts ending soon", `<p>The TOEFL ITP preparation program contract for <b>${esc(d.name)}</b> ends on <b>${esc(fmt(d.date))}</b> (${esc(d.days)} days from now). After that, access for all participants ends.</p><p>Contact the English Inspira administrator to extend it.</p>`) }),
  analysis_ready: (d: D) => ({ subject: "Your learning result analysis is ready", html: wrap("Analysis ready", `<p>The analysis for <b>${esc(d.title)}</b> is ready, with a narrative and suggested next steps.</p>${btn(String(d.link), "Open analysis")}`) }),
  itp_registered: (d: D) => ({ subject: "TOEFL ITP registration received", html: wrap("Registration received", `<p>Hello ${esc(d.name)}, we have received your registration for <b>${esc(d.title)}</b>.</p><p>Schedule: ${esc(fmt(d.date))}<br>Venue: ${esc(d.place)}</p><p>Arrive 30 minutes early and bring your original ID card/passport.</p>`) }),
  booking_confirmed: (d: D) => ({ subject: "Coaching booking confirmed", html: wrap("Booking confirmed", `<p>Coaching session with <b>${esc(d.coach)}</b>: ${esc(fmt(d.startsAt))}.</p><p>${d.mode === "online" ? `Link: ${esc(d.meetingUrl)}` : `Room: ${esc(d.room)}`}</p>`) }),
  slot_changed: (d: D) => ({ subject: "Coaching schedule changed", html: wrap("Schedule changed", `<p>Your coaching session was moved by the coach to ${esc(fmt(d.startsAt))}. If it does not suit you, cancel and choose another slot; your quota is not reduced.</p>${btn(String(d.link), "See schedule")}`) }),
  slot_cancelled: (d: D) => ({ subject: "Coaching session cancelled by the coach", html: wrap("Session cancelled", `<p>The session on ${esc(fmt(d.startsAt))} was cancelled by the coach. <b>Your quota is not reduced.</b> Please choose a replacement slot.</p>${btn(String(d.link), "Choose a slot")}`) }),
  session_reminder: (d: D) => ({ subject: "Reminder: coaching session tomorrow", html: wrap("Session reminder", `<p>Your coaching session: ${esc(fmt(d.startsAt))}.</p><p>${d.mode === "online" ? `Link: ${esc(d.meetingUrl)}` : `Room: ${esc(d.room)}`}</p>`) }),
  plan_deadline: (d: D) => ({ subject: "Your study plan deadline is approaching", html: wrap("Study plan reminder", `<p>The following items are due soon:</p><ul>${((d.items as string[]) ?? []).map((i) => `<li>${esc(i)}</li>`).join("")}</ul>${btn(String(d.link), "Open plan")}`) }),
  quota_low: (d: D) => ({ subject: "Coaching quota almost used up", html: wrap("Coaching quota", `<p>Your remaining coaching quota: <b>${esc(d.left)}</b> sessions.</p>`) }),
} satisfies Record<string, (d: D) => { subject: string; html: string }>;

export type TemplateName = keyof typeof TEMPLATES;
export const render = (t: TemplateName, d: D) => TEMPLATES[t](d);
